### PR TITLE
fix responsive and  issues 

### PR DESCRIPTION
**Pull request by iAreful**

### CODE REVIEW

**Comment by shalzz** [comment]
The website does not build properly
```
Module not found: Can't resolve '../components/Nav'
> 1 | import Nav from "../components/Nav";
  2 | import HeroSection from "../components/HeroSection";
  3 | import Footer from "./../components/Footer";
  4 | import CTAOne from "../components/CTAOne";

https://nextjs.org/docs/messages/module-not-found
```

**Comment by shalzz** [comment]
The icons used are incorrect from the design file
Screenshot from 2023-04-19 11-42-05

**Comment by shalzz** [comment]
The faq and subscribe section do not align properly as per the design
image
design:
image

**Comment by shalzz** [comment]
Share your email id here for proper design access and directly use the icons from zeplin

**Comment by iAreful** [comment]
temp email  lalafoxland@gmail.com

**Comment by shalzz** [comment]
No drop shadow on the signup email box

image

**Comment by shalzz** [comment]
Wrong icon used for menu button on mobile

image

**Review by shalzz — APPROVED** [review]

**Pull request merged**
